### ISSUE TITLE
Default Login Credentials?

### ISSUE THREAD

**Issue by cathalgarvey** [syncloud/nextcloud#3]
I just set up Syncloud, and installed Nextcloud.. now when I click the icon, I hit the nextcloud login screen. What are the default credentials, though? I've tried my syncloud credentials, no luck.

I'm otherwise very impressed by the ease of Syncloud, great job!

**Comment by cyberb** [comment]
You shiuld use device login/password used in activation process.
You could send us logs if you want from settings page so we could help you in case there is some other error.

**Comment by cathalgarvey** [comment]
Yea, I tried those and re-tried now. I also tried a "fake" fully-qualified username, like '<device username>@<device subdomain>.syncloud.it', but no luck that way, either. I tried my syncloud sign-up email and the device password, and I tried the syncloud sign up email and the syncloud password, also. :/

I've had other issues with setup so far (like being unable to set "external" in Syncloud.. it keeps silently reverting to "not", and the cert is still self-signed..), but this one's kinda the worst. Nextcloud was what turned me onto Syncloud.

**Comment by cathalgarvey** [comment]
I've clicked the "send logs" button in Syncloud, the subdomain is "cunningprojects.syncloud.it".

**Comment by cathalgarvey** [comment]
Possibly related from the logs (which I just received):

```
file: /var/log/sam.log

2017-01-03 14:17:06,892 - sam.manager - ERROR - self.occ.run('ldap:set-config s01 ldapTLS 0')
2017-01-03 14:17:06,893 - sam.manager - ERROR - File "/opt/app/nextcloud/lib/syncloud-owncloud-22/owncloud/octools.py", line 11, in run
2017-01-03 14:17:06,894 - sam.manager - ERROR - output = check_output('{0} {1}'.format(self.occ_runner_path, args), shell=True).strip()
2017-01-03 14:17:06,895 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/subprocess.py", line 573, in check_output
2017-01-03 14:17:06,916 - sam.manager - ERROR - raise CalledProcessError(retcode, cmd, output=output)
2017-01-03 14:17:06,918 - sam.manager - ERROR - subprocess.CalledProcessError: Command '/opt/app/nextcloud/bin/occ-runner ldap:set-config s01 ldapTLS 0' returned non-zero exit status 1
2017-01-03 14:17:07,065 - app - ERROR - unable to run /opt/app/nextcloud/bin/post-install
Traceback (most recent call last):
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 38, in run
    data = runner()
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 58, in <lambda>
    run(lambda: call(method, vars(args)), args.debug, text, exit_code_on_error)
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 17, in call
    return func(**params)
  File "/opt/app/sam/lib/syncloud-sam-79/syncloud_sam/manager.py", line 196, in install
    self.install_file(app_archive_filename)
  File "/opt/app/sam/lib/syncloud-sam-79/syncloud_sam/manager.py", line 228, in install_file
    self.run_hook(app_id, 'post-install')
  File "/opt/app/sam/lib/syncloud-sam-79/syncloud_sam/manager.py", line 268, in run_hook
    raise Exception(message)
Exception: unable to run /opt/app/nextcloud/bin/post-install
```

So the nextcloud post-install script died somewhere, maybe that's to blame?

**Comment by cyberb** [comment]
Yes, looks like there was an error during the activation, could you reactivate device again?

Also you should not use email as you device login, try entering something simple as user/password and then use exactly the same user/password in nextcloud login.
Also you may want to reinstall nextcloud as well.

As to external access you need to have UPnP enabled on your router for that:
````
2017-01-03 18:16:52,200 - check_mapper - WARNING - NatPmpPortMapper mapper failed, message: NATPMPUnsupportedError(-11, 'The gateway does not support NAT-PMP'), {}
2017-01-03 18:16:52,202 - UpnpClient - INFO - initializing upnp
2017-01-03 18:16:55,237 - check_mapper - WARNING - UpnpPortMapper mapper failed, message: Exception('Invalid Action',), {}
2017-01-03 18:16:55,238 - check_mapper - ERROR - None of mappers are working
2017-01-03 18:16:55,239 - Device - ERROR - Will not change access mode. Was not able to get working port drill.
````

**Comment by cyberb** [comment]
Also check the following issues and workarounds, as they are causing problems until we fix them in the next release:

Fix Let's encrypt support (real HTTPS certs): https://github.com/syncloud/platform/issues/213
Resize: https://github.com/syncloud/platform/issues/195
UPnP: https://github.com/syncloud/platform/issues/199

**Comment by cathalgarvey** [comment]
Ah, thanks. I assumed syncloud was doing reverse tunnelling. I'll try resetting the device, then, and see if that works!

On 3 January 2017 18:43:21 GMT+00:00, Boris Rybalkin <notifications@github.com> wrote:
>Yes, looks like there was an error during the activation, could you
>reactivate device again?
>
>Also you should not use email as you device login, try entering
>something simple as user/password and then use exactly the same
>user/password in nextcloud login.
>Also you may want to reinstall nextcloud as well.
>
>As to external access you need to have UPnP enabled on your router for
>that:
>````
>2017-01-03 18:16:52,200 - check_mapper - WARNING - NatPmpPortMapper
>mapper failed, message: NATPMPUnsupportedError(-11, 'The gateway does
>not support NAT-PMP'), {}
>2017-01-03 18:16:52,202 - UpnpClient - INFO - initializing upnp
>2017-01-03 18:16:55,237 - check_mapper - WARNING - UpnpPortMapper
>mapper failed, message: Exception('Invalid Action',), {}
>2017-01-03 18:16:55,238 - check_mapper - ERROR - None of mappers are
>working
>2017-01-03 18:16:55,239 - Device - ERROR - Will not change access mode.
>Was not able to get working port drill.
>````
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncloud/nextcloud/issues/3#issuecomment-270189669

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cyberb** [comment]
Just realised that you can loging to Syncloud web UI (same credentials are used for all the apps) then it must be just nextcloud installation issue. 
Probably reinstall should help, while we would like to know why

**Comment by Yury-MonZon** [comment]
Can't login as well. What shall I do?

**Comment by cyberb** [comment]
Are you talking abiut Syncloud web UI or nextcloud?

**Comment by Yury-MonZon** [comment]
Nextcloud.

**Comment by cyberb** [comment]
Send us logs from Syncloud settings page so we can help.

**Comment by Yury-MonZon** [comment]
Done. Thanks
